# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1158, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1920, 1098))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("asset/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalWidget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.horizontalWidget.setStyleSheet("background-color:rgba(238, 238, 238, 100)")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalWidget_2 = QtWidgets.QWidget(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_2.sizePolicy().hasHeightForWidth())
        self.verticalWidget_2.setSizePolicy(sizePolicy)
        self.verticalWidget_2.setMinimumSize(QtCore.QSize(500, 100))
        self.verticalWidget_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.verticalWidget_2.setStyleSheet("border:solid;\n"
"border-radius:3px;\n"
"border-color:rgb(185, 185, 185);\n"
"border-width:2px")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalWidget_5 = QtWidgets.QWidget(self.verticalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_5.sizePolicy().hasHeightForWidth())
        self.verticalWidget_5.setSizePolicy(sizePolicy)
        self.verticalWidget_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalWidget_5.setStyleSheet("border:none")
        self.verticalWidget_5.setObjectName("verticalWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalWidget = QtWidgets.QWidget(self.verticalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.modelType = QtWidgets.QComboBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(9)
        self.modelType.setFont(font)
        self.modelType.setStyleSheet("\n"
"QComboBox {\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;  \n"
"    min-width: 9em;  \n"
"\n"
"    border-style:dashed;\n"
"    border-width:2px;\n"
"    border-color:rgb(185, 185, 185);\n"
"    background-color:rgb(238, 238, 238);\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 50px;\n"
"\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.modelType.setObjectName("modelType")
        self.modelType.addItem("")
        self.modelType.addItem("")
        self.verticalLayout_6.addWidget(self.modelType)
        self.label = QtWidgets.QLabel(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"margin-bottom:10px\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.textIn = QtWidgets.QTextEdit(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textIn.sizePolicy().hasHeightForWidth())
        self.textIn.setSizePolicy(sizePolicy)
        self.textIn.setMaximumSize(QtCore.QSize(550, 200))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        self.textIn.setFont(font)
        self.textIn.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textIn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textIn.setAutoFillBackground(False)
        self.textIn.setStyleSheet("margin-bottom: 10px;\n"
"border:solid;\n"
"border-radius:3px;\n"
"border-color:rgb(185, 185, 185);\n"
"border-width:2px\n"
"\n"
"")
        self.textIn.setObjectName("textIn")
        self.verticalLayout_6.addWidget(self.textIn)
        self.verticalLayout_5.addWidget(self.verticalWidget)
        self.verticalWidget1 = QtWidgets.QWidget(self.verticalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget1.sizePolicy().hasHeightForWidth())
        self.verticalWidget1.setSizePolicy(sizePolicy)
        self.verticalWidget1.setStyleSheet("border:none")
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:none;\n"
"margin-bottom:10px")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.textOutMt5 = QtWidgets.QTextEdit(self.verticalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textOutMt5.sizePolicy().hasHeightForWidth())
        self.textOutMt5.setSizePolicy(sizePolicy)
        self.textOutMt5.setMaximumSize(QtCore.QSize(550, 16000000))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        self.textOutMt5.setFont(font)
        self.textOutMt5.setStyleSheet("border:solid;\n"
"border-radius:3px;\n"
"border-color:rgb(185, 185, 185);\n"
"border-width:2px")
        self.textOutMt5.setReadOnly(True)
        self.textOutMt5.setObjectName("textOutMt5")
        self.verticalLayout.addWidget(self.textOutMt5)
        self.verticalLayout_5.addWidget(self.verticalWidget1)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.verticalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(0, 60))
        self.horizontalWidget_2.setStyleSheet("border:none")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.horizontalWidget_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Mt5Button_3 = QtWidgets.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mt5Button_3.sizePolicy().hasHeightForWidth())
        self.Mt5Button_3.setSizePolicy(sizePolicy)
        self.Mt5Button_3.setMinimumSize(QtCore.QSize(0, 45))
        self.Mt5Button_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Mt5Button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Mt5Button_3.setStyleSheet("border:solid;\n"
"border-radius:3px;\n"
"border-color:rgb(200, 200, 200);\n"
"border-width:2px")
        self.Mt5Button_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("asset/textout1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Mt5Button_3.setIcon(icon1)
        self.Mt5Button_3.setIconSize(QtCore.QSize(32, 32))
        self.Mt5Button_3.setObjectName("Mt5Button_3")
        self.verticalLayout_7.addWidget(self.Mt5Button_3)
        self.verticalLayout_5.addWidget(self.horizontalWidget_2)
        self.verticalLayout_3.addWidget(self.verticalWidget_5)
        self.horizontalLayout_2.addWidget(self.verticalWidget_2)
        self.verticalWidget_21 = QtWidgets.QWidget(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_21.sizePolicy().hasHeightForWidth())
        self.verticalWidget_21.setSizePolicy(sizePolicy)
        self.verticalWidget_21.setMinimumSize(QtCore.QSize(400, 0))
        self.verticalWidget_21.setStyleSheet("border:solid;\n"
"border-radius:3px;\n"
"border-color:rgb(185, 185, 185);\n"
"border-width:2px")
        self.verticalWidget_21.setObjectName("verticalWidget_21")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_21)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.upload = QtWidgets.QPushButton(self.verticalWidget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload.setStyleSheet("border:dashed;\n"
"border-radius:3px;\n"
"border-color:rgb(185, 185, 185);\n"
"border-width:2px")
        self.upload.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("asset/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload.setIcon(icon2)
        self.upload.setIconSize(QtCore.QSize(100, 100))
        self.upload.setObjectName("upload")
        self.verticalLayout_4.addWidget(self.upload)
        self.AckButton = QtWidgets.QPushButton(self.verticalWidget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AckButton.sizePolicy().hasHeightForWidth())
        self.AckButton.setSizePolicy(sizePolicy)
        self.AckButton.setMinimumSize(QtCore.QSize(0, 90))
        self.AckButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AckButton.setMouseTracking(False)
        self.AckButton.setStyleSheet("border:solid;\n"
"border-radius:3px;\n"
"border-color:rgb(185, 185, 185);\n"
"border-width:2px")
        self.AckButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("asset/ack3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AckButton.setIcon(icon3)
        self.AckButton.setIconSize(QtCore.QSize(64, 64))
        self.AckButton.setObjectName("AckButton")
        self.verticalLayout_4.addWidget(self.AckButton)
        self.horizontalLayout_2.addWidget(self.verticalWidget_21)
        self.verticalLayout_2.addWidget(self.horizontalWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "文本摘要器"))
        self.modelType.setItemText(0, _translate("Form", "MT文本摘要模型"))
        self.modelType.setItemText(1, _translate("Form", "MT对话摘要模型"))
        self.label.setText(_translate("Form", "文本输入"))
        self.label_7.setText(_translate("Form", "文本输出"))
