# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(664, 750)
        Dialog.setStyleSheet("background-color:#F5F5F5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget = QtWidgets.QWidget(Dialog)
        self.verticalWidget.setStyleSheet("")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSpacing(32)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalWidget_2 = QtWidgets.QWidget(self.verticalWidget)
        self.verticalWidget_2.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px;\n"
"border-radius:6px;\n"
"font:24px\n"
"")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_3.setSpacing(32)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 64))
        font = QtGui.QFont()
        font.setFamily("13")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"font:24px bold;\n"
"color:#F5F5F5")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalWidget_21 = QtWidgets.QWidget(self.verticalWidget_2)
        self.verticalWidget_21.setStyleSheet("border:none")
        self.verticalWidget_21.setObjectName("verticalWidget_21")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalWidget_21)
        self.verticalLayout_10.setSpacing(48)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.verticalWidget_21)
        self.horizontalWidget_2.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_4.setContentsMargins(-1, 8, 180, 8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 48))
        self.label_2.setStyleSheet("margin-right:26px;\n"
"border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"font:16px bold;\n"
"color:#F5F5F5")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalWidget_5 = QtWidgets.QWidget(self.horizontalWidget_2)
        self.horizontalWidget_5.setStyleSheet("border:none")
        self.horizontalWidget_5.setObjectName("horizontalWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalWidget_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.serverIp = QtWidgets.QLineEdit(self.horizontalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverIp.sizePolicy().hasHeightForWidth())
        self.serverIp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.serverIp.setFont(font)
        self.serverIp.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px;")
        self.serverIp.setObjectName("serverIp")
        self.horizontalLayout_7.addWidget(self.serverIp)
        self.horizontalLayout_4.addWidget(self.horizontalWidget_5)
        self.verticalLayout_10.addWidget(self.horizontalWidget_2)
        self.horizontalWidget = QtWidgets.QWidget(self.verticalWidget_21)
        self.horizontalWidget.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(-1, 8, 180, 8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 48))
        self.label_3.setStyleSheet("margin-right:12px;\n"
"border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"font:16px bold;\n"
"color:#F5F5F5")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalWidget_5 = QtWidgets.QWidget(self.horizontalWidget)
        self.verticalWidget_5.setStyleSheet("border:none")
        self.verticalWidget_5.setObjectName("verticalWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalWidget_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.serverPort = QtWidgets.QLineEdit(self.verticalWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverPort.sizePolicy().hasHeightForWidth())
        self.serverPort.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.serverPort.setFont(font)
        self.serverPort.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px;")
        self.serverPort.setObjectName("serverPort")
        self.verticalLayout_6.addWidget(self.serverPort)
        self.horizontalLayout.addWidget(self.verticalWidget_5)
        self.verticalLayout_10.addWidget(self.horizontalWidget)
        self.verticalLayout_3.addWidget(self.verticalWidget_21, 0, QtCore.Qt.AlignVCenter)
        self.verticalWidget_2.raise_()
        self.label.raise_()
        self.verticalLayout.addWidget(self.verticalWidget_2, 0, QtCore.Qt.AlignVCenter)
        self.verticalWidget_3 = QtWidgets.QWidget(self.verticalWidget)
        self.verticalWidget_3.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px;\n"
"border-radius:6px;\n"
"font:24px\n"
"")
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_4.setSpacing(32)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 64))
        self.label_4.setStyleSheet("border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding:5px;\n"
"font:24px bold;\n"
"color:#F5F5F5")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.verticalWidget_8 = QtWidgets.QWidget(self.verticalWidget_3)
        self.verticalWidget_8.setStyleSheet("border:none")
        self.verticalWidget_8.setObjectName("verticalWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalWidget_8)
        self.verticalLayout_11.setSpacing(48)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalWidget_4 = QtWidgets.QWidget(self.verticalWidget_8)
        self.horizontalWidget_4.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px")
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_6.setContentsMargins(-1, -1, 180, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 48))
        self.label_5.setStyleSheet("border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"font:16px bold;\n"
"color:#F5F5F5")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalWidget_6 = QtWidgets.QWidget(self.horizontalWidget_4)
        self.verticalWidget_6.setStyleSheet("border:none")
        self.verticalWidget_6.setObjectName("verticalWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalWidget_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.coding = QtWidgets.QLineEdit(self.verticalWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coding.sizePolicy().hasHeightForWidth())
        self.coding.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.coding.setFont(font)
        self.coding.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px;")
        self.coding.setObjectName("coding")
        self.verticalLayout_7.addWidget(self.coding)
        self.horizontalLayout_6.addWidget(self.verticalWidget_6)
        self.verticalLayout_11.addWidget(self.horizontalWidget_4)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.verticalWidget_8)
        self.horizontalWidget_3.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px")
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 180, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 48))
        self.label_6.setStyleSheet("margin-right:23px;\n"
"border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"font:16px bold;\n"
"color:#F5F5F5")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalWidget_7 = QtWidgets.QWidget(self.horizontalWidget_3)
        self.verticalWidget_7.setStyleSheet("border:none")
        self.verticalWidget_7.setObjectName("verticalWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalWidget_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.outputDir = QtWidgets.QLineEdit(self.verticalWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDir.sizePolicy().hasHeightForWidth())
        self.outputDir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outputDir.setFont(font)
        self.outputDir.setStyleSheet("border-style:solid;\n"
"border-color:#BDBDBD;\n"
"border-width:2px;")
        self.outputDir.setObjectName("outputDir")
        self.verticalLayout_8.addWidget(self.outputDir)
        self.horizontalLayout_5.addWidget(self.verticalWidget_7)
        self.verticalLayout_11.addWidget(self.horizontalWidget_3)
        self.verticalLayout_4.addWidget(self.verticalWidget_8)
        self.verticalLayout.addWidget(self.verticalWidget_3)
        self.horizontalWidget1 = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_3.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_3.setSpacing(143)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveButton = QtWidgets.QPushButton(self.horizontalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setStyleSheet("border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"font:12px bold;\n"
"color:#F5F5F5")
        self.saveButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("asset/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon)
        self.saveButton.setIconSize(QtCore.QSize(24, 24))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.resetButton = QtWidgets.QPushButton(self.horizontalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMaximumSize(QtCore.QSize(16777215, 48))
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setStyleSheet("border:none;\n"
"background-color:#607D8B;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"font:12px bold;\n"
"color:#F5F5F5")
        self.resetButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("asset/Reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon1)
        self.resetButton.setIconSize(QtCore.QSize(24, 24))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.verticalLayout.addWidget(self.horizontalWidget1)
        self.verticalLayout_2.addWidget(self.verticalWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Setting"))
        self.label.setText(_translate("Dialog", "Server Config"))
        self.label_2.setText(_translate("Dialog", "Server IP"))
        self.label_3.setText(_translate("Dialog", "Server Port"))
        self.label_4.setText(_translate("Dialog", "Basic Config"))
        self.label_5.setText(_translate("Dialog", "Coding Config"))
        self.label_6.setText(_translate("Dialog", "Output Dir"))
